version: '3.8'

services:
  db:
    image: postgres:13.6-alpine
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    # ボリューム：コンテナが終了してもデータを永続的に保管して置けるデータ領域
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data

  api:
    build:
      # Dockerfileの保存場所がdocker-compose.ymlと異なる場合はcontextで指定、名前がDockerfileでないときはDockerfile: ファイル名で指定する
      context: ./api
      # Dockerfileへ環境変数を渡す
      args:
        WORKDIR: $WORKDIR
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      API_DOMAIN: "localhost:$FRONT_PORT"
    volumes:
      - ./api:/$WORKDIR
    # 他コンテナとの依存関係
    depends_on:
      - db
    ports:
      - "$API_PORT:$CONTAINER_PORT"

  front:
    build:
      context: ./front
      args:
        WORKDIR: $WORKDIR
        CONTAINER_PORT: $CONTAINER_PORT
        API_URL: "http://localhost:$API_PORT"
    command: yarn run dev
    volumes:
      - ./front:/$WORKDIR
      - /$WORKDIR/node_modules
    ports:
      - "$FRONT_PORT:$CONTAINER_PORT"
    depends_on:
      - api
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true