version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    working_dir: "/src"
    # volumesでコンテナ内にデータ保持
    volumes:
      - "./src:/src"
      - node_modules_volume:/src/node_modules
    # コンテナの起動を維持
    tty: true
    environment:
    - CHOKIDAR_USEPOLLING=true
volumes:
  node_modules_volume: